// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logger} from '../models';

export function LogFromFrontend(arg1:logger.FrontendLogEntry):Promise<void>;
