// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllNodes() {
  return window['go']['main']['App']['GetAllNodes']();
}

export function GetMapBackground() {
  return window['go']['main']['App']['GetMapBackground']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveMapBackground(arg1, arg2) {
  return window['go']['main']['App']['SaveMapBackground'](arg1, arg2);
}

export function SaveNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNode'](arg1, arg2, arg3);
}

export function UpdateNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2, arg3, arg4);
}
