// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetAllNodes():Promise<Array<dto.Node>>;

export function GetMapBackground():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveMapBackground(arg1:string,arg2:string):Promise<string>;

export function SaveNode(arg1:string,arg2:number,arg3:number):Promise<number>;

export function UpdateNode(arg1:number,arg2:string,arg3:number,arg4:number):Promise<void>;
